app/models.py
from app import db
from flask import url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import login


class Image(db.Model):
    """Image location in the filesystem and relevant metadata"""
    id = db.Column(db.Integer, primary_key=True)
    upload_date = db.Column(db.DateTime, index=True)
    filename = db.Column(db.Unicode(255), index=True, unique=True)
    size = db.Column(db.Integer)
    name = db.Column(db.Unicode(255))
    caption = db.Column(db.Unicode(500))
    last_modified_date = db.Column(db.DateTime)
    homepage_ind = db.Column(db.Boolean, default=False)


    def __repr__(self):
        return '<Image Metadata {}'.format(str(self.id) + ' ' + str(self.name) + ' '
                                           + str(self.size / 1000) + ' Filename:' + str(self.filename)
                                           )


    def api_to_dict(self):
        src = str(url_for('static', filename='images/' + self.filename, _external=True))
        image_dict = {'src': src,
                      'thumbnail': src,
                      'thumbnailWidth': 320,
                      'thumbnailHeight': 212
                      }
        return image_dict


class Admin(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64))
    password_hash = db.Column(db.String(500))


    def set_password(self, password):
        self.password_hash = generate_password_hash(password)


    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return Admin.query.get(int(id))

app/api/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileRequired


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class FileUpload(FlaskForm):
    file = FileField('Image', validators=[FileRequired()])
    is_homepage = BooleanField('Put this on the Homepage?', default=False)
    submit = SubmitField('Upload')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_mail import Mail
import logging
from logging.handlers import RotatingFileHandler
import os
from flask_bootstrap import Bootstrap
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
mail = Mail()
bootstrap = Bootstrap()
login = LoginManager()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    bootstrap.init_app(app)
    login.init_app(app)
    login.login_view = 'api.auth'

    from app.main import bp as main_bp

    app.register_blueprint(main_bp)

    from app.api import bp as api_bp

    app.register_blueprint(api_bp, url_prefix='/api')

    if not app.debug:
        if not os.path.exists('logs'):
            os.mkdir('logs')

        file_handler = RotatingFileHandler('logs/app_name.log', maxBytes=10240, backupCount=50)
        file_handler.setFormatter(
                logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Your App Startup')

    return app


from app import models

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import routes

app/api/auth.py
from app.models import Admin
from flask_login import login_user


def auth_user(username: str, password: str, remember: bool) -> bool:
    """
    @type username: object
    
    """
    user = Admin.query.filter_by(username=username).first()
    if user is None or not user.check_password(password):
        return False
    login_user(user, remember=remember)
    return True

app/api/routes.py
from flask import request, redirect, url_for, flash, render_template
from app.api import bp
from app.helpers import _construct_standard_response, _build_cors_preflight_response
from app.api.image_handling import allowed_file, write_image, write_file_metadata, read_file_metadata
from flask_login import current_user, logout_user, login_required
from app.api.forms import LoginForm, FileUpload
from app.api.auth import auth_user


@bp.route('/gallery-photos', methods=['GET', 'OPTIONS'])
def gallery_photos():
    if request.method == 'OPTIONS':
        return _build_cors_preflight_response()

    if request.method == 'GET':
        images = read_file_metadata()
        return _construct_standard_response(images)


@bp.route('/home-photos', methods=['GET', 'OPTIONS'])
def home_photos():
    if request.method == 'OPTIONS':
        return _build_cors_preflight_response()

    if request.method == 'GET':
        images = read_file_metadata(homepage=True)
        return _construct_standard_response(images)


@bp.route('/auth', methods=['POST', 'GET'])
def auth():
    if current_user.is_authenticated:
        return redirect(url_for('api.admin'))

    form = LoginForm()

    if form.validate_on_submit():
        if not auth_user(form.username.data, form.password.data, form.remember_me.data):
            flash('Invalid Username or Password')
            return redirect(url_for('api.auth'))

        return redirect(url_for('api.admin'))

    return render_template(
            'login.html',
            title='Sign In',
            form=form
    )


@bp.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    form = FileUpload()

    if form.validate_on_submit():
        file = form.file.data
        homepage_ind = form.is_homepage.data

        if file and allowed_file(file.filename):
            image_size, safe_filename = write_image(file)

            write_file_metadata(file, image_size, homepage_ind, safe_filename)

            return redirect(url_for('api.admin'))

        else:
            flash('This filetype is not allowed')
            return redirect(url_for('main.home'))

    return render_template(
            'image-upload.html',
            title='Admin',
            form=form
    )


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('api.auth'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp


@bp.route('/')
@bp.route('/home')
def home():
    return render_template(
            'base.html',
        title='Home',
    )

app/templates/base.html
<!doctype html>
<html>
    <head>
        {% if title %}
        <title>{{ title }} - Microblog</title>
        {% else %}
        <title>Welcome to Microblog</title>
        {% endif %}
    </head>
    <body>
        <div>
            Microblog:
            {% if current_user.is_anonymous %}
            <a href="{{ url_for('api.auth') }}">Login</a>
            {% else %}
            <a href="{{ url_for('api.logout') }}">Logout</a>
            {% endif %}
        </div>
        <hr>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </body>
</html>

app/templates/image-upload.html
{% extends "base.html" %}

{% block content %}
    <h1>Upload Image</h1>
    <form method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ form.file.label }}
        {{ form.file }}<br/>
        {{ form.is_homepage.label }}
        {{ form.is_homepage }}<br/>
        {{ form.submit }}
    </form>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
   {% endblock %}